### ISSUE TITLE
[Tracking] Arcade

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#123]
- [ ] Create arcade puzzle
- [ ] Edit arcade puzzle
- [ ] Create arcade collection
- [ ] Edit arcade collection
- [ ] Arcade homepage
- [ ] Browse arcade puzzles
- [ ] Browse arcade collections
- [ ] Arcade complexity score
- [ ] Arcade recommendation engine
