### ISSUE TITLE
[Tracking] Lab

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#133]
- [ ] Lab homepage
- [ ] Create initiative
- [ ] Edit initiative
- [ ] View initiative
- [ ] Create lab project
- [ ] Edit lab project
- [ ] View lab project
- [ ] Create experiment
- [ ] Edit experiment
- [ ] Download experiment designs
- [ ] Upload experiment data
- [ ] Design voting

**Comment by luxaritas** [comment]
The latest iteration of the taxonomy from our one-page
![image](https://user-images.githubusercontent.com/18635705/206606058-4a9dfe56-25e8-4ef3-b199-8d468550cfe2.png)
