### ISSUE TITLE
[Tracking] Library

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#153]
- [ ] Facade library page
- [ ] Library page
- [ ] Library search omnibox
- [ ] Create/edit library articles
- [ ] View library articles
- [ ] Library discussions
- [ ] Create/edit library notebooks
- [ ] View library notebooks
