### ISSUE TITLE
[Tracking] Help

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#162]
- [ ] Facade help page
- [ ] Help page
- [ ] Help omnibox
- [ ] Create help ticket
- [ ] Edit help ticket
- [ ] View help ticket
- [ ] Help ticket response
- [ ] Help ticket assignment
