### ISSUE TITLE
[Tracking] Moderation

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#200]
- [ ] Content reporting/flagging
- [ ] Moderator dashboard
- [ ] Ignore user
- [ ] Soft bans
- [ ] Full bans
- [ ] IP soft/full bans
- [ ] Ban appeal notification
- [ ] Spam auto-detection
