### ISSUE TITLE
[Tracking] Designer tools

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#253]
- [ ] Designer tool system
- [ ] Base Mutation
- [ ] User Mark
- [ ] Freeform annotation
- [ ] Change target pairing
- [ ] Add/remove base/pair
- [ ] Add/remove/split/edit oligo/strand
- [ ] Add/remove/edit ligand
- [ ] Add/remove switch state
- [ ] Undo/redo/history
- [ ] Change valid mutations
- [ ] Lock/unlock
- [ ] Add/remove/edit 3D
- [ ] Add/remove/edit template image
- [ ] Specify protein sequence
- [ ] Codon cycler
- [ ] Reset
- [ ] Copy
- [ ] Paste
- [ ] Screenshot/Export Image
- [ ] Manual 2D layout
