### ISSUE TITLE
[Tracking] Designer HUD

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#275]
- [ ] Design designer HUD
- [ ] Designer windowing
- [ ] Metrics / constraints UI
- [ ] RNAVis modifier UI
- [ ] Designer camera manipulation
- [ ] Designer toolbar UI
