### ISSUE TITLE
[Tracking] Design system (styles and standards)

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#29]
Tracking for high-level design system decisions. This includes:
- [ ] Scale (spacing and size)
- [ ] Color (global and semantic)
- [ ] Typography
- [ ] Object styles (motion, elevation, border radius, etc)
- [ ] Icon design
- [ ] Content (voice, tone, accessibility)
- [ ] Accessibility

**Comment by luxaritas** [comment]
Examples of existing design systems we're taking inspiration from:
- [Adobe Spectrum](https://spectrum.adobe.com/)
- [IBM Carbon](https://carbondesignsystem.com/)
- [Material Design](https://material.io/)
