### ISSUE TITLE
[Tracking] User flows and journies

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#42]
To better understand how our platform will work and how our users experience it, we will develop:
- [ ] User segments and personas (who are our users/what different classes of users do we have?)
- [ ] User flows (what do our users do on our platform, and how do they move between different parts of the platform?)
- [ ] User journeys (looking at different segments of user flows, at any given point what are the user's goals, outcomes, actions, needs/pains, touchpoints, and feelings and what opportunities can we identify for improvement?)
