### ISSUE TITLE
[Tracking] Design system (components)

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#50]
General Components
- [ ] Accordion (inkline: Collapsible)
- [ ] Alert
- [ ] Avatar
- [ ] Badge (notification)
- [ ] Breadcrumb
- [ ] Button
- [ ] Card
- [ ] Dialog
- [ ] Icon
- [ ] List
- [ ] Loader
- [ ] Nav
- [ ] Pill (inkline badge)
- [ ] Popover/tooltip
- [ ] Progress
- [ ] Tabs
- [ ] Table
- [ ] Toast

Form elements
- [ ] Form and form group
- [ ] Form label
- [ ] Input
- [ ] Textarea
- [ ] Rich text area
- [ ] Number input
- [ ] Date picker
- [ ] Color picker
- [ ] File picker
- [ ] Checkbox/toggle
- [ ] Radio button
- [ ] Select

**Comment by luxaritas** [comment]
We're planning on building our components on top of the [Inkline](https://www.inkline.io/) library. The idea is to help limit the amount we're re-inventing the wheel, plus they've probably thought more carefully around things like micro-interactions and accessibility where we may not do as good of a job. Inkline shouldn't have the issues we've seen with bootstrap (it's designed to be customizable, it's build to be tree-shaken, and it has a minimal dependency footprint, and doesn't require coordinating multiple libraries like we currently do with bootstrap and bootstrap-vue).

Our plan is to "wrap" inkline components in our own components, where they exist. That way:
1) We don't require new developers to understand inkline - just what we expose in our codebase
2) We can make any additional standard customizations we want
3) Custom components in our design system that inkline doesn't expose can be surfaced consistently with the ones it does expose
4) Admittedly, I have a bit of nervousness around inkline since it appears to only have one maintainer. If we need to, this provides us an easy way to swap out inline with something else (or our own implementation)

We also want to implement versions of these components in Figma to use in our mockups

**Comment by luxaritas** [comment]
Additional inspirations:
* [Vuetify 3](https://v3.vuetifyjs.com/en/components/all/)
* [Bootstrap](https://getbootstrap.com/docs/5.2/components/)
* [Carbon](https://carbondesignsystem.com/components/overview/)
