### ISSUE TITLE
[Tracking] Marketing

### ISSUE THREAD

**Issue by luxaritas** [eternagame/eterna-next#96]
- [ ] Main Landing Page
- [ ] Educator Landing Page
- [ ] Researcher Landing Page
- [ ] Press Landing Page
- [ ] Campaign Landing Page(s)
- [ ] Sofware Licensing
- [ ] Donation Page
- [ ] About/History Page
